[2022-10-28T01:08:32.382+0000] {processor.py:154} INFO - Started process (PID=7241) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:08:32.384+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:08:32.385+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:32.385+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:08:33.402+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:33.400+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:08:33.402+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:08:33.422+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.044 seconds
[2022-10-28T01:09:04.084+0000] {processor.py:154} INFO - Started process (PID=7327) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:04.102+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:09:04.103+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:04.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:05.110+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:05.109+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:09:05.111+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:05.138+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.058 seconds
[2022-10-28T01:09:35.621+0000] {processor.py:154} INFO - Started process (PID=7412) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:35.647+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:09:35.648+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:35.648+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:36.597+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:36.595+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:09:36.599+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:09:36.628+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.011 seconds
[2022-10-28T01:10:07.348+0000] {processor.py:154} INFO - Started process (PID=7514) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:07.351+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:10:07.352+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:07.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:08.308+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:08.306+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:10:08.309+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:08.337+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.993 seconds
[2022-10-28T01:10:38.731+0000] {processor.py:154} INFO - Started process (PID=7657) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:38.734+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:10:38.735+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:38.735+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:39.666+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:39.665+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:10:39.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:10:39.689+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.963 seconds
[2022-10-28T01:11:10.095+0000] {processor.py:154} INFO - Started process (PID=7797) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:10.096+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:11:10.097+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:10.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:11.117+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:11.116+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:11:11.118+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:11.140+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.049 seconds
[2022-10-28T01:11:41.550+0000] {processor.py:154} INFO - Started process (PID=7910) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:41.565+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:11:41.566+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:41.566+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:42.534+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:42.533+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:11:42.535+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:11:42.557+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.012 seconds
[2022-10-28T01:12:13.036+0000] {processor.py:154} INFO - Started process (PID=7994) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:13.061+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:12:13.062+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:13.062+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:14.047+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:14.046+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:12:14.048+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:14.068+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.036 seconds
[2022-10-28T01:12:44.480+0000] {processor.py:154} INFO - Started process (PID=8077) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:44.492+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:12:44.493+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:44.493+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:45.457+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:45.456+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:12:45.458+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:12:45.477+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.001 seconds
[2022-10-28T01:13:15.928+0000] {processor.py:154} INFO - Started process (PID=8089) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:15.931+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:13:15.932+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:15.932+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:16.943+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:16.942+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:13:16.944+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:16.966+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.042 seconds
[2022-10-28T01:13:47.389+0000] {processor.py:154} INFO - Started process (PID=8100) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:47.414+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:13:47.415+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:47.415+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:48.342+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:48.340+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:13:48.342+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:13:48.363+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.978 seconds
[2022-10-28T01:14:18.941+0000] {processor.py:154} INFO - Started process (PID=8183) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:18.960+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:14:18.960+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:18.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:19.791+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:19.790+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:14:19.791+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:19.816+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.061 seconds
[2022-10-28T01:14:50.232+0000] {processor.py:154} INFO - Started process (PID=8269) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:50.251+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:14:50.252+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:50.252+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:51.111+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:51.109+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:14:51.111+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:14:51.135+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.907 seconds
[2022-10-28T01:15:21.590+0000] {processor.py:154} INFO - Started process (PID=8352) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:21.611+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:15:21.613+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:21.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:22.477+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:22.475+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:15:22.477+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:22.501+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.916 seconds
[2022-10-28T01:15:52.957+0000] {processor.py:154} INFO - Started process (PID=8435) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:52.959+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:15:52.960+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:52.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:53.849+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:53.848+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:15:53.850+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:15:53.868+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.916 seconds
[2022-10-28T01:16:24.344+0000] {processor.py:154} INFO - Started process (PID=8518) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:24.354+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:16:24.355+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:24.355+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:25.241+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:25.239+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:16:25.241+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:25.263+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.923 seconds
[2022-10-28T01:16:55.465+0000] {processor.py:154} INFO - Started process (PID=8616) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:55.493+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:16:55.494+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:55.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:56.320+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:56.319+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:16:56.320+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:16:56.339+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.878 seconds
[2022-10-28T01:17:26.491+0000] {processor.py:154} INFO - Started process (PID=8627) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:26.505+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:17:26.506+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:26.506+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:27.392+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:27.391+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:17:27.393+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:27.414+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.927 seconds
[2022-10-28T01:17:57.604+0000] {processor.py:154} INFO - Started process (PID=8638) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:57.607+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:17:57.608+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:57.608+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:58.533+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:58.532+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:17:58.534+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:17:58.563+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.965 seconds
[2022-10-28T01:18:28.729+0000] {processor.py:154} INFO - Started process (PID=8752) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:18:28.731+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:18:28.732+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:28.732+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:18:29.612+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:29.610+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:18:29.613+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:18:29.635+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.911 seconds
[2022-10-28T01:18:59.843+0000] {processor.py:154} INFO - Started process (PID=8878) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:18:59.860+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:18:59.862+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:59.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:00.735+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:00.734+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'TB_CARTEIRA'
[2022-10-28T01:19:00.735+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:00.756+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.919 seconds
[2022-10-28T01:19:05.935+0000] {processor.py:154} INFO - Started process (PID=8895) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:05.936+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:19:05.937+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:05.937+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:06.835+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:06.834+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 12, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:19:06.836+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:06.856+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.926 seconds
[2022-10-28T01:19:22.031+0000] {processor.py:154} INFO - Started process (PID=8987) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:22.057+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:19:22.058+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:22.058+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:22.861+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:22.860+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:19:22.862+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:22.880+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.854 seconds
[2022-10-28T01:19:53.206+0000] {processor.py:154} INFO - Started process (PID=9214) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:53.209+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:19:53.210+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:53.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:54.129+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:19:54.126+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:19:54.129+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:19:54.149+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.947 seconds
[2022-10-28T01:20:05.399+0000] {processor.py:154} INFO - Started process (PID=9244) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:05.401+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:20:05.401+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:05.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:06.273+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:06.271+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
  File "airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'carga_tb_carteira' (most likely due to a circular import) (airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:20:06.274+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:06.308+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.914 seconds
[2022-10-28T01:20:13.300+0000] {processor.py:154} INFO - Started process (PID=9274) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:13.315+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:20:13.316+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:13.316+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:14.112+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:14.110+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:20:14.112+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:14.134+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.839 seconds
[2022-10-28T01:20:38.925+0000] {processor.py:154} INFO - Started process (PID=9347) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:38.926+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:20:38.927+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:38.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:39.758+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:39.756+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:20:39.758+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:39.778+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.858 seconds
[2022-10-28T01:20:42.407+0000] {processor.py:154} INFO - Started process (PID=9350) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:42.410+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:20:42.412+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:42.411+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:43.347+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:20:43.402+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:43.401+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:20:43.421+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:20:43.421+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:20:43.337958+00:00, run_after=2022-10-29T01:20:43.337958+00:00
[2022-10-28T01:20:43.463+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.060 seconds
[2022-10-28T01:21:13.579+0000] {processor.py:154} INFO - Started process (PID=9397) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:13.581+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:21:13.581+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:13.581+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:14.468+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:14.516+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:14.515+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:21:14.540+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:14.540+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:21:14.460365+00:00, run_after=2022-10-29T01:21:14.460365+00:00
[2022-10-28T01:21:14.574+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.999 seconds
[2022-10-28T01:21:22.584+0000] {processor.py:154} INFO - Started process (PID=9438) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:22.591+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:21:22.592+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:22.592+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:23.391+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:23.399+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:23.399+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:21:23.420+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:23.419+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:21:23.382482+00:00, run_after=2022-10-29T01:21:23.382482+00:00
[2022-10-28T01:21:23.450+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.870 seconds
[2022-10-28T01:21:53.731+0000] {processor.py:154} INFO - Started process (PID=9450) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:53.734+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:21:53.735+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:53.735+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:54.670+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:21:54.735+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:54.734+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:21:54.766+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:21:54.765+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:21:54.657368+00:00, run_after=2022-10-29T01:21:54.657368+00:00
[2022-10-28T01:21:54.802+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 1.076 seconds
[2022-10-28T01:22:04.820+0000] {processor.py:154} INFO - Started process (PID=9492) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:04.821+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:22:04.822+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:04.822+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:05.662+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:05.670+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:05.669+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:22:05.693+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:05.692+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:22:05.652890+00:00, run_after=2022-10-29T01:22:05.652890+00:00
[2022-10-28T01:22:05.722+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.906 seconds
[2022-10-28T01:22:22.844+0000] {processor.py:154} INFO - Started process (PID=9584) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:22.846+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:22:22.847+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:22.846+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:23.677+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:23.687+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:23.686+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T01:22:23.710+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:23.710+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T01:22:23.666407+00:00, run_after=2022-10-29T01:22:23.666407+00:00
[2022-10-28T01:22:23.740+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.901 seconds
[2022-10-28T01:22:27.183+0000] {processor.py:154} INFO - Started process (PID=9600) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:27.184+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:22:27.185+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:27.185+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:27.189+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:27.188+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14
    from tb_carteira. import create_datalake
                      ^
SyntaxError: invalid syntax
[2022-10-28T01:22:27.190+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:27.222+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.044 seconds
[2022-10-28T01:22:29.384+0000] {processor.py:154} INFO - Started process (PID=9602) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:29.387+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:22:29.388+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:29.388+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:30.274+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:22:30.272+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:22:30.275+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:22:30.305+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.927 seconds
[2022-10-28T01:23:00.681+0000] {processor.py:154} INFO - Started process (PID=9650) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:00.724+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:00.725+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:00.725+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:01.575+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:01.574+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:23:01.576+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:01.598+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.922 seconds
[2022-10-28T01:23:31.800+0000] {processor.py:154} INFO - Started process (PID=9731) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:31.805+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:31.806+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:31.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:32.664+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:32.662+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 14, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:23:32.664+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:32.684+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.888 seconds
[2022-10-28T01:23:35.216+0000] {processor.py:154} INFO - Started process (PID=9734) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:35.217+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:35.218+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:35.218+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:36.065+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:36.064+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:23:36.066+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:36.086+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.878 seconds
[2022-10-28T01:23:38.851+0000] {processor.py:154} INFO - Started process (PID=9749) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:38.852+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:38.853+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:38.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:39.761+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:39.759+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:23:39.761+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:39.781+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.937 seconds
[2022-10-28T01:23:41.961+0000] {processor.py:154} INFO - Started process (PID=9753) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:41.962+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:41.963+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:41.963+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:42.855+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:42.853+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    import sys,sleep
ModuleNotFoundError: No module named 'sle'
[2022-10-28T01:23:42.855+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:42.876+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.919 seconds
[2022-10-28T01:23:47.180+0000] {processor.py:154} INFO - Started process (PID=9772) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:47.183+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:47.184+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:47.184+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:48.040+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:48.039+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 15, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:23:48.041+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:48.062+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 0.886 seconds
[2022-10-28T01:23:52.289+0000] {processor.py:154} INFO - Started process (PID=9789) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:23:52.294+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:23:52.295+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:23:52.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:24:22.297+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:24:22.296+0000] {timeout.py:68} ERROR - Process timed out, PID: 9789
[2022-10-28T01:24:22.298+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:24:22.298+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 13, in <module>
    time.sleep(48)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9789
[2022-10-28T01:24:22.299+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:24:22.321+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 30.037 seconds
[2022-10-28T01:24:52.511+0000] {processor.py:154} INFO - Started process (PID=9951) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:24:52.525+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:24:52.526+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:24:52.525+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:25:22.528+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:25:22.527+0000] {timeout.py:68} ERROR - Process timed out, PID: 9951
[2022-10-28T01:25:22.529+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:25:22.528+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 13, in <module>
    time.sleep(48)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9951
[2022-10-28T01:25:22.530+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:25:22.552+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 30.047 seconds
[2022-10-28T01:25:52.739+0000] {processor.py:154} INFO - Started process (PID=10330) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:25:52.744+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:25:52.746+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:25:52.745+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:26:22.748+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:26:22.747+0000] {timeout.py:68} ERROR - Process timed out, PID: 10330
[2022-10-28T01:26:22.750+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:26:22.748+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 13, in <module>
    time.sleep(48)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 10330
[2022-10-28T01:26:22.750+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:26:22.775+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 30.041 seconds
[2022-10-28T01:26:52.958+0000] {processor.py:154} INFO - Started process (PID=10565) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:26:52.968+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:26:52.970+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:26:52.969+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:27:22.972+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:27:22.971+0000] {timeout.py:68} ERROR - Process timed out, PID: 10565
[2022-10-28T01:27:22.974+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:27:22.973+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 13, in <module>
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 10565
[2022-10-28T01:27:22.975+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py
[2022-10-28T01:27:23.001+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py took 30.048 seconds
