[2022-10-28T00:55:31.901+0000] {processor.py:154} INFO - Started process (PID=4637) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:55:31.902+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:55:31.903+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:55:31.903+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:55:31.909+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:55:31.907+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 1, in <module>
    from airflow.providers.google.cloud.operators.bigquery import  (
ModuleNotFoundError: No module named 'airflow.providers.google'
[2022-10-28T00:55:31.909+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:55:31.939+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.044 seconds
[2022-10-28T00:58:31.971+0000] {processor.py:154} INFO - Started process (PID=4931) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:58:32.003+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:58:32.006+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:58:32.005+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:58:32.860+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:58:32.868+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:58:32.867+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T00:58:32.891+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:58:32.891+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T00:58:32.852261+00:00, run_after=2022-10-29T00:58:32.852261+00:00
[2022-10-28T00:58:33.071+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.106 seconds
[2022-10-28T00:59:03.250+0000] {processor.py:154} INFO - Started process (PID=5012) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:03.260+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:59:03.262+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:03.262+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:04.092+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:04.143+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:04.143+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T00:59:04.162+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:04.162+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T00:59:04.084347+00:00, run_after=2022-10-29T00:59:04.084347+00:00
[2022-10-28T00:59:04.198+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.953 seconds
[2022-10-28T00:59:34.732+0000] {processor.py:154} INFO - Started process (PID=5093) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:34.733+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:59:34.734+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:34.734+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:35.565+0000] {processor.py:766} INFO - DAG(s) dict_keys(['carga_tb_carteira']) retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:35.615+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:35.615+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-10-28T00:59:35.635+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:35.635+0000] {dag.py:3336} INFO - Setting next_dagrun for carga_tb_carteira to 2022-10-28T00:59:35.557016+00:00, run_after=2022-10-29T00:59:35.557016+00:00
[2022-10-28T00:59:35.828+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.099 seconds
[2022-10-28T00:59:56.022+0000] {processor.py:154} INFO - Started process (PID=5164) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:56.058+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:59:56.059+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:56.059+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:56.063+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:56.062+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00
         ^
SyntaxError: invalid syntax
[2022-10-28T00:59:56.064+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:56.098+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.082 seconds
[2022-10-28T00:59:59.004+0000] {processor.py:154} INFO - Started process (PID=5177) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:59.006+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T00:59:59.008+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:59.007+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:59.013+0000] {logging_mixin.py:120} INFO - [2022-10-28T00:59:59.011+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 
         ^
SyntaxError: invalid syntax
[2022-10-28T00:59:59.013+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T00:59:59.048+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.051 seconds
[2022-10-28T01:00:11.231+0000] {processor.py:154} INFO - Started process (PID=5244) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:11.233+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:00:11.233+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:00:11.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:11.237+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:00:11.235+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00_create_datalake import 
           ^
SyntaxError: invalid decimal literal
[2022-10-28T01:00:11.238+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:11.264+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.037 seconds
[2022-10-28T01:00:41.565+0000] {processor.py:154} INFO - Started process (PID=5395) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:41.582+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:00:41.583+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:00:41.583+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:41.588+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:00:41.586+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00_create_datalake import 
           ^
SyntaxError: invalid decimal literal
[2022-10-28T01:00:41.588+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:00:41.629+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.069 seconds
[2022-10-28T01:01:04.769+0000] {processor.py:154} INFO - Started process (PID=5518) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:04.777+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:01:04.778+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:04.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:04.783+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:04.781+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00_create_datalake import create_datalake
           ^
SyntaxError: invalid decimal literal
[2022-10-28T01:01:04.783+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:04.818+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.054 seconds
[2022-10-28T01:01:09.839+0000] {processor.py:154} INFO - Started process (PID=5546) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:09.840+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:01:09.841+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:09.841+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:09.844+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:09.843+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00_create_datalake import create_datalake
           ^
SyntaxError: invalid decimal literal
[2022-10-28T01:01:09.845+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:09.874+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.039 seconds
[2022-10-28T01:01:40.184+0000] {processor.py:154} INFO - Started process (PID=5701) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:40.188+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:01:40.189+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:40.189+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:40.193+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:40.191+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from 00_create_datalake import create_datalake
           ^
SyntaxError: invalid decimal literal
[2022-10-28T01:01:40.194+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:40.230+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.049 seconds
[2022-10-28T01:01:45.260+0000] {processor.py:154} INFO - Started process (PID=5731) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:45.261+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:01:45.262+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:45.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:46.206+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:01:46.205+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from create_datalake_01 import create_datalake
ModuleNotFoundError: No module named 'create_datalake_01'
[2022-10-28T01:01:46.207+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:01:46.225+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.970 seconds
[2022-10-28T01:02:10.594+0000] {processor.py:154} INFO - Started process (PID=5851) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:10.597+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:10.599+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:10.598+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:11.623+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:11.622+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from airflow. import create_datalake
ModuleNotFoundError: No module named 'air'
[2022-10-28T01:02:11.623+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:11.644+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.056 seconds
[2022-10-28T01:02:17.540+0000] {processor.py:154} INFO - Started process (PID=5879) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:17.542+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:17.542+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:17.542+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:17.546+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:17.545+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from airflow.dags. import create_datalake
                       ^
SyntaxError: invalid syntax
[2022-10-28T01:02:17.546+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:17.575+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.041 seconds
[2022-10-28T01:02:18.692+0000] {processor.py:154} INFO - Started process (PID=5881) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:18.693+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:18.694+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:18.694+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:19.774+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:19.772+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from airflow.dags.TB_CARTEIRA import create_datalake
ModuleNotFoundError: No module named 'airflow.dags'
[2022-10-28T01:02:19.775+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:19.805+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.119 seconds
[2022-10-28T01:02:20.964+0000] {processor.py:154} INFO - Started process (PID=5883) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:20.966+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:20.967+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:20.967+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:20.971+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:20.969+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10
    from airflow.dags.TB_CARTEIRA. import create_datalake
                                   ^
SyntaxError: invalid syntax
[2022-10-28T01:02:20.971+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:21.006+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.046 seconds
[2022-10-28T01:02:26.022+0000] {processor.py:154} INFO - Started process (PID=5899) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:26.023+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:26.023+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:26.023+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:27.051+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:27.050+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from airflow.dags.TB_CARTEIRA.carga_tb_carteira. import create_datalake
ModuleNotFoundError: No module named 'airflow.dags'
[2022-10-28T01:02:27.052+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:27.075+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.058 seconds
[2022-10-28T01:02:29.213+0000] {processor.py:154} INFO - Started process (PID=5902) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:29.215+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:29.217+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:29.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:30.283+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:30.282+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from airflow.dags.TB_CARTEIRA.carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'airflow.dags'
[2022-10-28T01:02:30.284+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:30.307+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.099 seconds
[2022-10-28T01:02:39.793+0000] {processor.py:154} INFO - Started process (PID=5933) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:39.794+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:02:39.795+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:39.795+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:40.785+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:02:40.783+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'TB_CARTEIRA.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py)
[2022-10-28T01:02:40.786+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:02:40.809+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.021 seconds
[2022-10-28T01:03:11.263+0000] {processor.py:154} INFO - Started process (PID=6027) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:11.266+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:03:11.267+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:03:11.267+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:12.216+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:03:12.215+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'TB_CARTEIRA.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py)
[2022-10-28T01:03:12.217+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:12.239+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.981 seconds
[2022-10-28T01:03:42.627+0000] {processor.py:154} INFO - Started process (PID=6173) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:42.631+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:03:42.632+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:03:42.632+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:43.624+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:03:43.623+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'TB_CARTEIRA.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py)
[2022-10-28T01:03:43.624+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:03:43.645+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.022 seconds
[2022-10-28T01:04:13.908+0000] {processor.py:154} INFO - Started process (PID=6268) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:04:13.911+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:04:13.912+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:04:13.911+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:04:14.898+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:04:14.897+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'TB_CARTEIRA.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py)
[2022-10-28T01:04:14.899+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:04:14.920+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.016 seconds
[2022-10-28T01:05:14.860+0000] {processor.py:154} INFO - Started process (PID=6546) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:14.865+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:05:14.867+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:05:14.866+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:15.844+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:05:15.843+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py", line 10, in <module>
    from TB_CARTEIRA.carga_tb_carteira import create_datalake
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from tb_carteira.carga_tb_carteira import create_datalake
ImportError: cannot import name 'create_datalake' from partially initialized module 'tb_carteira.carga_tb_carteira' (most likely due to a circular import) (/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/tb_carteira/carga_tb_carteira.py)
[2022-10-28T01:05:15.845+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:15.865+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.010 seconds
[2022-10-28T01:05:31.152+0000] {processor.py:154} INFO - Started process (PID=6593) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:31.153+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:05:31.154+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:05:31.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:32.182+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:05:32.181+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:05:32.183+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:05:32.201+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.054 seconds
[2022-10-28T01:06:02.690+0000] {processor.py:154} INFO - Started process (PID=6676) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:02.715+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:06:02.716+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:06:02.716+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:03.712+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:06:03.711+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:06:03.713+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:03.734+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.048 seconds
[2022-10-28T01:06:33.911+0000] {processor.py:154} INFO - Started process (PID=6819) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:33.914+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:06:33.915+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:06:33.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:34.942+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:06:34.940+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:06:34.942+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:06:34.963+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.056 seconds
[2022-10-28T01:07:05.118+0000] {processor.py:154} INFO - Started process (PID=6972) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:05.138+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:07:05.139+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:07:05.139+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:06.079+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:07:06.078+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:07:06.080+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:06.101+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.987 seconds
[2022-10-28T01:07:36.231+0000] {processor.py:154} INFO - Started process (PID=7079) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:36.243+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:07:36.244+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:07:36.244+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:37.214+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:07:37.213+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:07:37.215+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:07:37.235+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.008 seconds
[2022-10-28T01:08:07.438+0000] {processor.py:154} INFO - Started process (PID=7161) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:07.455+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:08:07.456+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:07.456+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:08.369+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:08.368+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:08:08.369+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:08.388+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.955 seconds
[2022-10-28T01:08:38.553+0000] {processor.py:154} INFO - Started process (PID=7259) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:38.599+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:08:38.601+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:38.600+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:39.593+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:08:39.592+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:08:39.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:08:39.614+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.067 seconds
[2022-10-28T01:09:09.761+0000] {processor.py:154} INFO - Started process (PID=7342) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:09.775+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:09:09.776+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:09.776+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:10.812+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:10.810+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:09:10.812+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:10.836+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.079 seconds
[2022-10-28T01:09:40.914+0000] {processor.py:154} INFO - Started process (PID=7428) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:40.918+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:09:40.919+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:40.919+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:41.891+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:09:41.890+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:09:41.892+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:09:41.913+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.004 seconds
[2022-10-28T01:10:12.125+0000] {processor.py:154} INFO - Started process (PID=7530) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:12.146+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:10:12.147+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:12.147+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:13.141+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:13.140+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:10:13.142+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:13.163+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.043 seconds
[2022-10-28T01:10:43.333+0000] {processor.py:154} INFO - Started process (PID=7673) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:43.336+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:10:43.337+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:43.337+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:44.285+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:10:44.284+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:10:44.286+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:10:44.307+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.979 seconds
[2022-10-28T01:11:14.349+0000] {processor.py:154} INFO - Started process (PID=7817) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:14.352+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:11:14.353+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:14.353+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:15.272+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:15.271+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:11:15.272+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:15.293+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.948 seconds
[2022-10-28T01:11:45.448+0000] {processor.py:154} INFO - Started process (PID=7926) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:45.464+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:11:45.465+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:45.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:46.376+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:11:46.375+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:11:46.376+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:11:46.395+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.953 seconds
[2022-10-28T01:12:16.554+0000] {processor.py:154} INFO - Started process (PID=8009) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:16.557+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:12:16.557+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:16.557+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:17.572+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:17.570+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:12:17.573+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:17.595+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.046 seconds
[2022-10-28T01:12:47.690+0000] {processor.py:154} INFO - Started process (PID=8080) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:47.694+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:12:47.695+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:47.695+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:48.673+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:12:48.672+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:12:48.674+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:12:48.694+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.008 seconds
[2022-10-28T01:13:18.888+0000] {processor.py:154} INFO - Started process (PID=8091) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:18.892+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:13:18.894+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:18.894+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:19.874+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:19.873+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:13:19.874+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:19.894+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 1.011 seconds
[2022-10-28T01:13:50.084+0000] {processor.py:154} INFO - Started process (PID=8103) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:50.087+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:13:50.088+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:50.087+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:51.043+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:13:51.041+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:13:51.043+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:13:51.063+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.984 seconds
[2022-10-28T01:14:21.365+0000] {processor.py:154} INFO - Started process (PID=8186) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:21.368+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:14:21.369+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:21.368+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:22.190+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:22.189+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:14:22.191+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:22.214+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.854 seconds
[2022-10-28T01:14:52.303+0000] {processor.py:154} INFO - Started process (PID=8271) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:52.318+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:14:52.319+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:52.319+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:53.225+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:14:53.224+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:14:53.226+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:14:53.245+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.948 seconds
[2022-10-28T01:15:23.410+0000] {processor.py:154} INFO - Started process (PID=8354) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:23.431+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:15:23.432+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:23.431+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:24.239+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:24.238+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:15:24.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:24.259+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.854 seconds
[2022-10-28T01:15:54.406+0000] {processor.py:154} INFO - Started process (PID=8437) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:54.409+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:15:54.411+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:54.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:55.215+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:15:55.213+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:15:55.215+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:15:55.238+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.836 seconds
[2022-10-28T01:16:25.447+0000] {processor.py:154} INFO - Started process (PID=8521) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:25.485+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:16:25.486+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:25.486+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:26.382+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:26.381+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:16:26.383+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:26.402+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.959 seconds
[2022-10-28T01:16:56.597+0000] {processor.py:154} INFO - Started process (PID=8618) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:56.600+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:16:56.602+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:56.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:57.389+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:16:57.388+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:16:57.390+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:16:57.410+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.817 seconds
[2022-10-28T01:17:27.646+0000] {processor.py:154} INFO - Started process (PID=8629) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:27.649+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:17:27.651+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:27.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:28.458+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:28.456+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:17:28.458+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:28.479+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.838 seconds
[2022-10-28T01:17:58.689+0000] {processor.py:154} INFO - Started process (PID=8640) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:58.690+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:17:58.691+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:58.691+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:59.573+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:17:59.572+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:17:59.574+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:17:59.596+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.912 seconds
[2022-10-28T01:18:16.960+0000] {processor.py:154} INFO - Started process (PID=8709) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:16.988+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:18:16.989+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:16.989+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:17.841+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:17.840+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:18:17.842+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:17.872+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.916 seconds
[2022-10-28T01:18:25.031+0000] {processor.py:154} INFO - Started process (PID=8737) to work on /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:25.033+0000] {processor.py:756} INFO - Processing file /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py for tasks to queue
[2022-10-28T01:18:25.033+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:25.033+0000] {dagbag.py:537} INFO - Filling up the DagBag from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:25.807+0000] {logging_mixin.py:120} INFO - [2022-10-28T01:18:25.805+0000] {dagbag.py:342} ERROR - Failed to import: /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py", line 10, in <module>
    from carga_tb_carteira import create_datalake
ModuleNotFoundError: No module named 'carga_tb_carteira'
[2022-10-28T01:18:25.807+0000] {processor.py:768} WARNING - No viable dags retrieved from /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py
[2022-10-28T01:18:25.828+0000] {processor.py:176} INFO - Processing /home/marcelohenriqueleite35/carteira_ativos/airflow/dags/TB_CARTEIRA/carga_tb_carteira.py took 0.801 seconds
